image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -a src/* public/
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - master
