image: registry.gitlab.com/pages/hugo/hugo_extended:0.58.3

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "1"

stages:
  - build
  - deploy
  - trigger

hugo:
  stage: build
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master

pages:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  script:
    - echo deploying...
  dependencies:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master

clear_caches:
  variables:
    GIT_STRATEGY: none
  stage: trigger
  dependencies:
    - pages
  image: registry.access.redhat.com/ubi8/ubi-minimal:8.0
  script:
    - "curl -X DELETE \"https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache\" -H \"Authorization: Bearer $CLOUDFLARE_TOKEN\" -H 'Content-type: application/json' --data '{\"purge_everything\": true}'"
  only:
    - master
