image: registry.gitlab.com/pages/hugo/hugo_extended:0.58.3

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - deploy
  - trigger

pages:
  stage: deploy
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master

clear_caches:
  stage: trigger
  script:
    - "curl -X DELETE \"https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache\" -H \"Authorization: Bearer $CLOUDFLARE_TOKEN\" -H 'Content-type: application/json' --data '{\"purge_everything\": true}'"
  only:
    - master
