language: minimal

env:
  global:
    - HUGO_VER=0.58.3
    - HUGO_SHA1=e1c75f8566d8a755f9fce410b6c8b50560345163

git:
  submodules: true
  depth: 1

cache:
  directories:
    - ${HOME}/.my_cache

before_cache:
    - "echo ${HUGO_SHA1} ${HOME}/.my_cache/download/hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz | sha1sum --check --status || rm -f ${HOME}/.my_cache/download/hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz"

before_script:
  - "mkdir -p ${HOME}/.my_cache/download ${HOME}/bin"
  - "test -f ${HOME}/.my_cache/download/hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz || curl -L -o ${HOME}/.my_cache/download/hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz"
  - "echo ${HUGO_SHA1} ${HOME}/.my_cache/download/hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz | sha1sum --check"
  - "tar -xzvf ${HOME}/.my_cache/download/hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz -C ${HOME}/bin hugo"

script:
  - "${HOME}/bin/hugo"

before_deploy:
  - "echo ${GITHUB_DEPLOY_KEY} | base64 -d > ${HOME}/.github_deploy.key"
  - "find ."

deploy:
  provider: pages
  edge: true
  fqdn: colefamily.page
  repo: coleslawbrakers/colefamily.page
  target_branch: master
  local_dir: public
  skip_cleanup: true
  deploy_key: ${HOME}/.github_deploy.key
  keep_history: true
  verbose: true
  on:
    branch: master

after_deploy:
  - "curl -X DELETE \"https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache\" -H \"Authorization: Bearer ${CLOUDFLARE_TOKEN}\" -H 'Content-type: application/json' --data '{\"purge_everything\": true}'"
